const characters = {
	old_shixie: ["male", "qun", 3, ["biluan", "lixia"], ["die:shixie"]],
	panfeng: ["male", "qun", 4, ["kuangfu"]],
	old_guanyinping: ["female", "shu", 3, ["xueji_old", "oldhuxiao", "oldwuji"], ["die:guanyinping"]],
	old_caocao: ["male", "shen", 3, ["junkguixin", "feiying"], ["die:shen_caocao"]],
	old_chendao: ["male", "shu", 4, ["drlt_wanglie"], ["die:chendao"]],
	old_liyan: ["male", "shu", 3, ["duliang", "fulin"], ["die:liyan"]],
	old_guanzhang: ["male", "shu", 4, ["old_fuhun"], ["name:关|兴-张|苞"]],
	new_caoren: ["male", "wei", 4, ["moon_jushou", "jiewei"], ["die:caoren"]],
	huangzhong: ["male", "shu", 4, ["liegong"]],
	old_dingfeng: ["male", "wu", 4, ["fenxun", "duanbing"], ["die:dingfeng"]],
	old_huanghao: ["male", "shu", 3, ["oldqinqing", "oldhuisheng"], ["die:huanghao"]],
	oldre_liubiao: ["male", "qun", 3, ["zishou", "zongshi"], ["die:liubiao"]],
	old_liubiao: ["male", "qun", 4, ["oldzishou", "zongshi"], ["die:liubiao"]],
	old_gaoshun: ["male", "qun", 4, ["xianzhen", "jinjiu"], ["die:gaoshun"]],
	old_caorui: ["male", "wei", 3, ["huituo", "oldmingjian", "xingshuai"], ["zhu", "die:caorui"]],
	old_handang: ["male", "wu", 4, ["oldgongji", "oldjiefan"], ["die:handang"]],
	old_yangzhi: ["female", "jin", 3, ["wanyi", "maihuo"], ["die:yangzhi"]],
	old_yangyan: ["female", "jin", 3, ["xuanbei", "xianwan"], ["die:yangyan"]],
	madai: ["male", "shu", 4, ["mashu", "oldqianxi"]],
	xuhuang: ["male", "wei", 4, ["gzduanliang"]],
	junk_simayi: ["male", "jin", 3, ["buchen", "smyyingshi", "xiongzhi", "quanbian"], ["hiddenSkill", "name:司马|懿", "die:jin_simayi"]],
	fazheng: ["male", "shu", 3, ["enyuan", "xuanhuo"]],
	ol_yuanshu: ["male", "qun", 4, ["wangzun", "tongji"], ["die:re_yuanshu"]],
	pangde: ["male", "qun", 4, ["mashu", "mengjin"]],
	ol_huaxiong: ["male", "qun", 6, ["new_reyaowu"], ["die:old_huaxiong"]],
	old_wangyun: ["male", "qun", 4, ["wylianji", "moucheng"], ["clan:太原王氏", "die:wangyun"]],
	old_xiaoqiao: ["female", "wu", 3, ["tianxiang", "hongyan"], ["name:桥|null", "die:xiaoqiao"]],
	weiyan: ["male", "shu", 4, ["kuanggu"]],
	xiahouyuan: ["male", "wei", 4, ["shensu"], ["name:夏侯|渊"]],
	old_zhangxingcai: ["female", "shu", 3, ["oldshenxian", "qiangwu"], ["die:zhangxingcai"]],
	old_fuhuanghou: ["female", "qun", 3, ["oldzhuikong", "oldqiuyuan"], ["die:fuhuanghou"]],
	old_caochong: ["male", "wei", 3, ["oldrenxin", "oldchengxiang"], ["die:caochong"]],
	yuji: ["male", "qun", 3, ["old_guhuo"]],
	zhangjiao: ["male", "qun", 3, ["leiji", "guidao", "huangtian"], ["zhu"]],
	old_zhangfei: ["male", "shu", 4, ["new_repaoxiao", "new_tishen"], ["die:re_zhangfei"]],
	old_zhaoyun: ["male", "shu", 4, ["longdan", "new_yajiao"], ["die:re_zhaoyun"]],
	old_huatuo: ["male", "qun", 3, ["jijiu", "chulao"], ["die:re_huatuo"]],
	old_guanyu: ["male", "shu", 4, ["wusheng", "yijue"], ["die:re_guanyu"]],
	old_caochun: ["male", "wei", 4, ["shanjia"], ["die:caochun"]],
	masu: ["male", "shu", 3, ["xinzhan", "huilei"]],
	xushu: ["male", "shu", 3, ["xswuyan", "jujian"], ["border:wei"]],
	liru: ["male", "qun", 3, ["juece", "mieji", "fencheng"]],
	xin_yujin: ["male", "wei", 4, ["jieyue"], ["die:yujin.mp3"]],
	old_zhonghui: ["male", "wei", 3, ["zzhenggong", "zquanji", "zbaijiang"], ["clan:颍川钟氏"]],
	old_xusheng: ["male", "wu", 4, ["pojun"], ["die:xusheng"]],
	old_zhuran: ["male", "wu", 4, ["olddanshou"], ["die:zhuran"]],
	old_lingtong: ["male", "wu", 4, ["oldxuanfeng"], ["die:lingtong"]],
	old_caoxiu: ["male", "wei", 4, ["taoxi"], ["die:caoxiu"]],
	old_caozhen: ["male", "wei", 4, ["sidi"], ["die:caozhen"]],
	old_maliang: ["male", "shu", 3, ["xiemu", "naman"]],
	old_chenqun: ["male", "wei", 3, ["dingpin", "oldfaen"], ["die:chenqun"]],
	old_zhuhuan: ["male", "wu", 4, ["youdi"]],
	old_zhuzhi: ["male", "wu", 4, ["anguo"], ["die:zhuzhi"]],

	old_zhugezhan: ["male", "shu", 3, ["old_zuilun", "old_fuyin"], ["name:诸葛|瞻", "die:zhugezhan"]],
	//ol_manchong:['male','wei',3,['yuce','junxing']],
	old_guanqiujian: ["male", "wei", 4, ["drlt_zhenrong", "drlt_hongju"], ["name:毌丘|俭", "die:guanqiujian"]],
	old_wanglang: ["male", "wei", 3, ["gushe", "jici"], ["die:wanglang"]],
	old_wangyi: ["female", "wei", 3, ["oldzhenlie", "oldmiji"]],
	re_yujin: ["male", "wei", 4, ["yizhong"], ["die:yujin.mp3"]],
};

export default characters;
