window.noname_character_replace = {
	wuban: ["clan_wuban", "dc_wuban", "wuban", "xin_wuban", "ty_wuban"],
	key_yuri: ["key_yuri", "sp_key_yuri"],
	sp_key_kanade: ["sp_key_kanade", "kanade"],
	shen_zhangliao: ["ol_zhangliao", "shen_zhangliao"],
	shen_zhaoyun: ["shen_zhaoyun", "dc_zhaoyun", "old_shen_zhaoyun", "boss_zhaoyun"],
	shen_guanyu: ["shen_guanyu", "tw_shen_guanyu", "ty_shen_guanyu"],
	shen_sunquan: ["shen_sunquan", "junk_sunquan"],
	shen_lvmeng: ["shen_lvmeng", "tw_shen_lvmeng"],
	shen_machao: ["shen_machao", "ps_shen_machao"],
	shen_jiaxu: ["le_shen_jiaxu", "shen_jiaxu"],
	shen_caocao: ["shen_caocao", "old_caocao"],
	shen_zhangjiao: ["shen_zhangjiao", "junk_zhangjiao"],
	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo"],
	shen_simayi: ["shen_simayi", "xin_simayi", "new_simayi"],
	shen_liubei: ["shen_liubei", "ty_shen_liubei"],
	shen_zhangfei: ["shen_zhangfei", "ty_shen_zhangfei"],
	lifeng: ["dc_lifeng", "lifeng"],
	liuyong: ["liuyong", "jsrg_liuyong"],
	qiaorui: ["qiaorui", "tw_qiaorui"],
	gaoxiang: ["gaoxiang", "jsrg_gaoxiang"],
	zhangchu: ["zhangchu", "jsrg_zhangchu"],
	mamidi: ["mamidi", "xin_mamidi"],
	re_chunyuqiong: ["re_chunyuqiong", "chunyuqiong", "jsrg_chunyuqiong"],
	chengui: ["chengui", "mb_chengui"],
	qinlang: ["qinlang", "ol_qinlang"],
	caochun: ["caochun", "old_caochun"],
	majun: ["majun", "yj_majun", "cx_majun", "qq_majun", "old_majun"],
	zhanggong: ["zhanggong", "re_zhanggong"],
	baosanniang: ["xin_baosanniang", "re_baosanniang", "baosanniang"],
	heqi: ["re_heqi", "heqi"],
	weiwenzhugezhi: ["weiwenzhugezhi", "re_weiwenzhugezhi", "jsrg_weiwenzhugezhi"],
	xugong: ["xugong", "re_xugong", "jsrg_xugong"],
	liuzan: ["re_liuzan", "liuzan", "std_liuzan"],
	yj_sufei: ["yj_sufei", "sp_sufei", "xf_sufei"],
	jiakui: ["jiakui", "old_jiakui"],
	shenpei: ["shenpei", "sp_shenpei"],
	sunru: ["dc_sunru", "ol_sunru", "sunru"],
	liuye: ["dc_liuye", "liuye", "std_liuye"],
	zhaotongzhaoguang: ["dc_zhaotongzhaoguang", "zhaotongzhaoguang"],
	yangbiao: ["yangbiao", "dc_yangbiao", "jsrg_yangbiao"],
	qiaozhou: ["yj_qiaozhou", "qiaozhou", "tw_qiaozhou"],
	sunhanhua: ["dc_sunhanhua", "sunhanhua", "scl_sunhanhua"],
	zhoubuyi: ["zhoubuyi", "yj_zhoubuyi"],
	xianglang: ["xianglang", "mb_xianglang"],
	miheng: ["yue_miheng", "re_miheng", "miheng", "scl_miheng"],
	peixiu: ["ol_peixiu", "peixiu", "scl_peixiu", "fj_peixiu", "xj_peixiu"],
	chendeng: ["chendeng", "re_chendeng", "ol_chendeng", "jsrg_chendeng"],
	liuba: ["liuba", "ol_liuba", "dc_liuba"],
	lingcao: ["lingcao", "dc_lingcao"],
	liwan: ["ol_liwan", "liwan"],
	wuxian: ["wuxian", "clan_wuxian"],
	simafu: ["mb_simafu", "simafu", "yj_simafu"],
	xuangongzhu: ["yj_xuangongzhu", "xuangongzhu"],
	kebineng: ["kebineng", "ol_kebineng", "ddd_kebineng"],
	hanlong: ["hanlong", "jd_hanlong"],
	wuanguo: ["wuanguo", "ol_wuanguo"],
	ty_guanxing: ["ty_guanxing", "std_guanxing"],
    ty_fengxí: ["ty_fengxí", "tw_fengxí"],
    ty_zhangnan: ["ty_zhangnan", "tw_zhangnan"],
    ty_chenshi: ["ty_chenshi", "chenshi"],
    ty_anying: ["ty_anying", "ty_anyingx"],
	caoren: ["caoren", "old_caoren", "sb_caoren", "new_caoren", "star_caoren"],
	sp_caoren: ["sp_caoren", "jsp_caoren", "drag_caoren"],
	xiahouyuan: ["re_xiahouyuan", "ol_xiahouyuan", "xiahouyuan"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "huangzhong", "jsrg_huangzhong", "yj_huangzhong", "wuhujiang", "ty_huangzhong"],
	weiyan: ["re_weiyan", "ol_weiyan", "weiyan", "huan_weiyan", "yj_weiyan"],
	zhoutai: ["zhoutai", "xin_zhoutai", "old_zhoutai"],
	xiaoqiao: ["xiaoqiao", "ol_xiaoqiao", "re_xiaoqiao", "sb_xiaoqiao", "old_xiaoqiao", "jd_sb_xiaoqiao", "yue_xiaoqiao"],
	yuji: ["xin_yuji", "re_yuji", "yuji"],
	zhangjiao: ["sp_zhangjiao", "re_zhangjiao", "sb_zhangjiao", "jsrg_zhangjiao", "zhangjiao"],
	dianwei: ["dianwei", "ol_dianwei", "re_dianwei", "dc_sb_dianwei", "xia_dianwei"],
	xunyu: ["xunyu", "ol_xunyu", "re_xunyu", "sb_xunyu", "star_xunyu"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "tw_sb_sp_zhugeliang", , "jd_sb_sp_zhugeliang"],
	pangtong: ["pangtong", "ol_pangtong", "re_pangtong", "ol_sb_pangtong", "sb_pangtong", "jd_sb_pangtong"],
	re_jsp_pangtong: ["re_jsp_pangtong", "jsrg_pangtong", "sp_pangtong"],
	taishici: ["taishici", "re_taishici", "ol_sb_taishici", "pot_taishici"],
	re_yuanshao: ["re_yuanshao", "ol_yuanshao", "xin_yuanshao", "ol_sb_yuanshao", "star_yuanshao", "sb_yuanshao", "jd_sb_yuanshao", "jsrg_yuanshao", "yy_yuanshao"],
	pangde: ["re_pangde", "ol_pangde", "pangde", "sp_pangde"],
	yanwen: ["yanwen", "ol_yanwen", "re_yanwen"],
	tw_yanliang: ["tw_yanliang", "ns_yanliang"],
	tw_wenchou: ["tw_wenchou", "yy_wenchou"],
	caopi: ["caopi", "re_caopi", "ps_caopi", "sb_caopi", "tw_sb_caopi"],
	xuhuang: ["re_xuhuang", "ol_xuhuang", "sb_xuhuang", "xuhuang", "jd_sb_xuhuang", "yj_xuhuang"],
	menghuo: ["menghuo", "re_menghuo", "sb_menghuo", "sp_menghuo", "dc_sp_menghuo", "jd_sb_menghuo"],
	zhurong: ["zhurong", "ol_zhurong", "re_zhurong", "sb_zhurong", "dc_sp_zhurong"],
	sunjian: ["sunjian", "ol_sunjian", "re_sunjian", "star_sunjian", "ol_sb_sunjian", "jsrg_sunjian"],
	jiaxu: ["jiaxu", "re_jiaxu", "ns_jiaxu", "ps_jiaxu", "dc_sb_jiaxu", "sb_jiaxu"],
	dongzhuo: ["dongzhuo", "ol_dongzhuo", "re_dongzhuo", "star_dongzhuo", "jsrg_dongzhuo", "ol_sb_dongzhuo", "sp_dongzhuo", "yj_dongzhuo", "new_yj_dongzhuo"],
	dengai: ["dengai", "ol_dengai", "re_dengai", "jsrg_dengai", "ol_sb_dengai"],
	sp_ol_zhanghe: ["sp_ol_zhanghe", "yj_zhanghe", "tw_yj_zhanghe", "sp_zhanghe", "jsrg_zhanghe", "huan_zhanghe"],
	jiangwei: ["jiangwei", "ol_jiangwei", "re_jiangwei", "ol_sb_jiangwei", "sb_jiangwei", "jsrg_jiangwei", "huan_jiangwei", "jd_sb_jiangwei", "sp_jiangwei"],
	liushan: ["liushan", "ol_liushan", "re_liushan", "huan_liushan"],
	sunce: ["sunce", "re_sunce", "re_sunben", "sb_sunce", "dc_sunce", "jsrg_sunce", "sp_sunce"],
	zhangzhang: ["zhangzhang", "ol_zhangzhang", "re_zhangzhang", "tw_zhangzhao", "tw_zhanghong", "star_zhangzhao"],
	zuoci: ["zuoci", "re_zuoci"],
	caiwenji: ["caiwenji", "ol_caiwenji", "re_caiwenji", "yue_caiwenji", "sp_caiwenji"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou"],
	guanqiujian: ["guanqiujian", "re_guanqiujian", "tw_guanqiujian", "mb_sp_guanqiujian", "old_guanqiujian"],
	chendao: ["chendao", "ns_chendao", "old_chendao"],
	zhugezhan: ["zhugezhan", "old_zhugezhan"],
	ol_lusu: ["re_lusu", "ol_lusu", "dc_sb_lusu", "xia_lusu"],
	zhanghe: ["zhanghe", "re_zhanghe", "sb_zhanghe"],
	yl_luzhi: ["yl_luzhi", "jsrg_yl_luzhi", "sb_yl_luzhi", "tw_yl_luzhi"],
	sunliang: ["sunliang", "xin_sunliang"],
	zhoufei: ["zhoufei", "yue_zhoufei"],
	lukang: ["lukang", "jsrg_lukang"],
	wangcan: ["wangcan", "sp_wangcan", "tw_wangcan"],
	sunshao: ["sunshao", "sp_sunshao", "std_sunshao"],
	xunchen: ["xunchen", "re_xunchen", "sp_xunchen", "tw_xunchen", "clan_xunchen"],
	xinpi: ["xinpi", "sp_xinpi"],
	duyu: ["duyu", "dc_duyu", "sp_duyu", "pk_sp_duyu"],
	zhangwen: ["zhangwen", "sp_zhangwen"],
	ol_bianfuren: ["ol_bianfuren", "sp_bianfuren", "tw_bianfuren"],
	wangshuang: ["wangshuang", "sp_wangshuang"],
	huaman: ["huaman", "sp_huaman"],
	gaolan: ["gaolan", "dc_gaolan", "sp_gaolan"],
	cuiyan: ["cuiyan", "sp_cuiyan"],
	wujing: ["wujing", "ol_wujing", "tw_wujing"],
	zhouchu: ["jin_zhouchu", "zhouchu", "tw_zhouchu", "std_zhouchu"],
	liuzhang: ["liuzhang", "tw_liuzhang", "std_liuzhang"],
	sp_chenzhen: ["sp_chenzhen", "tw_chenzhen"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi", "std_feiyi"],
	wangling: ["dc_wangling", "wangling", "tw_wangling", "clan_wangling"],
	qiaogong: ["qiaogong", "tw_qiaogong"],
	sp_chendong: ["sp_chendong", "tw_chendong", "chendong"],
	sp_jiangqing: ["sp_jiangqing", "tw_jiangqing", "jiangqing", "dc_jiangqing"],
	kongrong: ["ol_sb_kongrong", "dc_kongrong", "sp_kongrong", "jsrg_kongrong", "kongrong"],
	dc_mifuren: ["dc_mifuren", "sp_mifuren"],
	sp_jiangwan: ["ol_jiangwan", "sp_jiangwan", "std_jiangwan"],
	sunhao: ["sunhao", "std_sunhao"],
	lvlingqi: ["lvlingqi", "std_lvlingqi"],
	chengyu: ["chengyu", "std_chengyu", "dc_sb_chengyu"],
	fanyufeng: ["fanyufeng", "std_fanyufeng"],
	yuejin: ["yuejin", "std_yuejin"],
	chenlin: ["chenlin", "dc_sb_chenlin"],
	shamoke: ["shamoke", "ty_shamoke"],
	guanyinping: ["guanyinping", "old_guanyinping", "ty_guanyinping"],
	shixie: ["shixie", "dc_shixie", "old_shixie"],
	caoshuang: ["caoshuang", "dc_caoshuang", "ns_caoshuang"],
	caoang: ["caoang", "yj_caoang", "tw_caoang"],
	caohong: ["caohong", "tw_re_caohong", "tw_caohong", "yj_caohong"],
	xiahouba: ["xiahouba", "dc_xiahouba", "tw_xiahouba", "std_xiahouba"],
	maliang: ["maliang", "re_maliang", "tw_maliang", "ol_maliang", "old_maliang", "std_maliang"],
	dingfeng: ["dingfeng", "tw_dingfeng", "old_dingfeng", "std_dingfeng"],
	zumao: ["zumao", "tw_zumao"],
	tw_beimihu: ["beimihu", "tw_beimihu"],
	panfeng: ["panfeng", "re_panfeng", "std_panfeng"],
	sunluyu: ["sunluyu", "re_sunluyu", "mb_sunluyu"],
	jin_simazhao: ["jin_simazhao", "simazhao", "sp_simazhao", "jd_jin_simazhao", "jsrg_simazhao", "jin_jsrg_simazhao"],
	jin_wangyuanji: ["jin_wangyuanji", "wangyuanji", "sp_wangyuanji", "std_wangyuanji", "jd_jin_wangyuanji"],
	wangyun: ["clan_wangyun", "wangyun", "dc_wangyun", "re_wangyun", "jsrg_wangyun", "old_wangyun", "pe_wangyun", "std_wangyun"],
	zhangliang: ["xin_zhangliang", "re_zhangliang", "zhangliang"],
	lingju: ["lingju", "old_lingju"],
	guansuo: ["guansuo", "dc_guansuo", "std_guansuo"],
	zhangxingcai: ["zhangxingcai", "old_zhangxingcai"],
	lisu: ["ol_lisu", "lisu"],
	fuwan: ["fuwan", "tw_fuwan", "sp_fuwan"],
	huaxin: ["ol_huaxin", "huaxin", "sp_huaxin", "std_huaxin", "jd_ol_huaxin"],
	xujing: ["xujing", "dc_xujing", "sp_xujing", "tw_xujing"],
	zhaoxiang: ["zhaoxiang", "dc_zhaoxiang", "tw_zhaoxiang"],
	dengzhi: ["ol_dengzhi", "re_dengzhi", "dengzhi", "tw_dengzhi", "std_re_dengzhi"],
	wangrong: ["ol_wangrong", "wangrong"],
	zongyu: ["zongyu", "sp_zongyu", "tw_zongyu"],
	ol_dongzhao: ["ol_dongzhao", "dc_dongzhao", "tw_dongzhao", "pot_dongzhao"],
	mayunlu: ["mayunlu", "tw_mayunlu", "std_mayunlu"],
	zhuling: ["ol_zhuling", "dc_zhuling", "zhuling"],
	zangba: ["zangba", "tw_zangba"],
	zhangbao: ["zhangbao", "re_zhangbao"],
	jianggan: ["jianggan", "sp_jianggan", "std_jianggan"],
	dc_jiben: ["dc_jiben", "sp_jiben"],
	yangyi: ["ol_yangyi", "yangyi", "tw_yangyi"],
	tianyu: ["tianyu", "tw_tianyu"],
	huangchengyan: ["huangchengyan", "dc_huangchengyan"],
	puyuan: ["ol_puyuan", "puyuan"],
	huangzu: ["huangzu", "dc_huangzu"],
	huojun: ["huojun", "dc_huojun", "xin_huojun", "tw_huojun"],
	zhaoyǎn: ["zhaoyǎn", "dc_zhaoyǎn"],
	furong: ["ol_furong", "furong", "tw_furong"],
	daxiaoqiao: ["daxiaoqiao", "dc_daxiaoqiao", "tw_daxiaoqiao"],
	zhugeguo: ["zhugeguo", "tw_zhugeguo", "yue_zhugeguo", "huan_zhugeguo"],
	wanglang: ["ol_wanglang", "wanglang", "old_wanglang", "std_wanglang"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan"],
	zhangyì: ["ol_zhangyì", "zhangyì", "std_zhangyì"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang"],
	ruiji: ["ruiji", "dc_ruiji"],
	jsp_huangyueying: ["jsp_huangyueying", "re_jsp_huangyueying"],
	ganfuren: ["ganfuren", "dc_ganfuren", "jsp_ganfuren", "mb_ganfuren"],
	zhouqun: ["ol_zhouqun", "zhouqun"],
	qianzhao: ["ol_qianzhao", "qianzhao"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang", "std_pengyang"],
	ol_luyusheng: ["ol_luyusheng", "luyusheng"],
	fanjiangzhangda: ["fanjiangzhangda", "jsrg_fanjiangzhangda"],
	simalang: ["re_simalang", "simalang"],
	zhugedan: ["re_zhugedan", "zhugedan", "jsrg_zhugedan"],
	jsrg_zhangren: ["jsrg_zhangren", "dc_zhangren"],
	ol_wenqin: ["ol_wenqin", "pe_wenqin", "mb_wenqin"],
	lukai: ["ol_lukai", "lukai"],
	liupi: ["ol_liupi", "liupi"],
	kanze: ["kanze", "re_kanze"],
	lvfan: ["lvfan", "sp_lvfan", "std_lvfan"],
	dongbai: ["dongbai", "re_dongbai", "jsrg_dongbai"],
	sp_jiaxu: ["dc_sp_jiaxu", "yj_jiaxu", "sp_jiaxu"],
	duji: ["duji", "re_duji", "ns_duji"],
	sp_taishici: ["sp_taishici", "re_sp_taishici"],
	mazhong: ["mazhong", "re_mazhong", "tw_mazhong"],
	wenpin: ["wenpin", "re_wenpin"],
	liuyan: ["liuyan", "jsrg_liuyan", "junk_liuyan"],
	buzhi: ["buzhi", "ty_buzhi"],
	hanfu: ["hanfu", "ol_hanfu"],
	niufu: ["niufu", "ol_niufu"],
	dongxie: ["dongxie", "ol_dongxie"],
	caoying: ["caoying", "scl_caoying"],
	xuelingyun: ["xuelingyun", "ol_xuelingyun", "ddd_xuelingyun"],
	lijue: ["lijue", "ns_lijue", "std_lijue"],
	fanchou: ["fanchou", "tw_fanchou", "ns_fanchou"],
	zhangji: ["zhangji", "ns_zhangji"],
	zhangchangpu: ["ol_zhangchangpu", "zhangchangpu", "sp_zhangchangpu"],
	huangfusong: ["huangfusong", "sp_huangfusong", "jsrg_huangfusong", "old_huangfusong"],
	dingyuan: ["ol_dingyuan", "dingyuan"],
	quyi: ["quyi", "re_quyi", "yy_quyi"],
	hansui: ["hansui", "re_hansui", "xin_hansui", "jsrg_hansui"],
	jin_simashi: ["dc_simashi", "jin_simashi", "simashi", "tw_simashi", "std_simashi", "jd_jin_simashi"],
	jin_yanghuiyu: ["jin_yanghuiyu", "yanghuiyu"],
	taoqian: ["re_taoqian", "taoqian", "std_taoqian"],
	jsp_liubei: ["jsrg_liubei", "jsp_liubei"],
	dongcheng: ["re_dongcheng", "dongcheng"],
	hucheer: ["re_hucheer", "hucheer", "tw_hucheer", "dc_sb_hucheer"],
	nanhualaoxian: ["re_nanhualaoxian", "ol_nanhualaoxian", "nanhualaoxian", "jsrg_nanhualaoxian"],
	pangdegong: ["re_pangdegong", "pangdegong", "scl_pangdegong"],
	zhujun: ["ol_zhujun", "zhujun", "sp_zhujun", "jsrg_zhujun"],
	tw_liuhong: ["liuhong", "tw_liuhong", "jsrg_liuhong"],
	re_hejin: ["hejin", "re_hejin", "tw_hejin", "jsrg_hejin"],
	hujinding: ["dc_hujinding", "ol_hujinding", "hujinding"],
	caosong: ["caosong", "sp_caosong"],
	re_niujin: ["niujin", "re_niujin", "tw_niujin"],
	haomeng: ["haomeng", "tw_haomeng"],
	zhangning: ["zhangning", "tw_zhangning"],
	caoanmin: ["caoanmin", "ns_caoanmin"],
	duanwei: ["duanwei", "junk_duanwei"],
	xushao: ["xushao", "jsrg_xushao"],
	ol_huban: ["ol_huban", "dc_huban", "mb_huban"],
	ol_mengda: ["ol_mengda", "dc_mengda", "pe_mengda"],
	jsp_guanyu: ["jsp_guanyu", "dc_jsp_guanyu", "tw_jsp_guanyu", "jsrg_guanyu"],
	mushun: ["mushun", "sp_mushun"],
	wangjun: ["dc_wangjun", "wangjun", "jsrg_wangjun"],
	re_zoushi: ["yue_zoushi", "re_zoushi", "jsrg_zoushi"],
	dc_zhangmancheng: ["dc_zhangmancheng", "tw_zhangmancheng"],
	xf_huangquan: ["xf_huangquan", "dc_huangquan"],
	re_zoushi: ["re_zoushi", "jsrg_zoushi", "yue_zoushi"],
	lvkuanglvxiang: ["lvkuanglvxiang", "dc_lvkuanglvxiang"],
	caocao: ["caocao", "re_caocao", "sb_caocao", "dc_caocao", "jd_sb_caocao", "jsrg_caocao", "sp_ol_caocao"],
	guojia: ["guojia", "re_guojia", "yj_sb_guojia", "ps1059_guojia", "ps2070_guojia", "jsrg_guojia", "sb_guojia"],
	simayi: ["simayi", "re_simayi", "dc_sb_simayi", "jsrg_simayi", "ps_simayi", "ps2068_simayi", "yy_simayi"],
	jin_simayi: ["jin_simayi", "junk_simayi", "huan_simayi", "ps_jin_simayi"],
	zhenji: ["zhenji", "re_zhenji", "sb_zhenji", "yj_zhenji"],
	xuzhu: ["xuzhu", "re_xuzhu"],
	zhangliao: ["zhangliao", "re_zhangliao", "sb_zhangliao", "v_zhangliao"],
	sp_zhangliao: ["sp_zhangliao", "yj_zhangliao", "jsrg_zhangliao"],
	xiahoudun: ["xiahoudun", "re_xiahoudun", "xin_xiahoudun", "sb_xiahoudun", "xia_xiahoudun", "sp_xiahoudun"],
	liubei: ["liubei", "re_liubei", "sb_liubei", "dc_liubei", "junk_liubei", "jd_sb_liubei", "ty_liubei", "xia_liubei", "sp_liubei", "jsrg_liubei"],
	guanyu: ["guanyu", "re_guanyu", "ol_sb_guanyu", "sb_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu", "wuhujiang", "jx_guanyu", "jd_sb_guanyu", "ty_guanyu", "xia_guanyu", "drag_guanyu"],
	zhangfei: ["zhangfei", "re_zhangfei", "old_zhangfei", "xin_zhangfei", "sb_zhangfei", "tw_zhangfei", "jsrg_zhangfei", "yj_zhangfei", "wuhujiang", "jd_sb_zhangfei", "sp_zhangfei", "ol_sb_zhangfei"],
	zhaoyun: ["zhaoyun", "re_zhaoyun", "old_zhaoyun", "sb_zhaoyun", "jsrg_zhaoyun", "ps2063_zhaoyun", "ps2067_zhaoyun", "huan_zhaoyun", "wuhujiang", "jd_sb_zhaoyun", "ol_sb_zhaoyun"],
	sp_zhaoyun: ["sp_zhaoyun", "jsp_zhaoyun", "yy_zhaoyun"],
	machao: ["machao", "re_machao", "sb_machao", "ps_machao", "wuhujiang"],
	sp_machao: ["sp_machao", "dc_sp_machao", "jsrg_machao", "old_machao"],
	zhugeliang: ["zhugeliang", "re_zhugeliang", "ps2066_zhugeliang", "ps_zhugeliang", "huan_zhugeliang", "jsrg_zhugeliang"],
	huangyueying: ["huangyueying", "re_huangyueying", "junk_huangyueying", "sb_huangyueying", "jd_sb_huangyueying", "ol_sb_huangyueying"],
	sunquan: ["sunquan", "re_sunquan", "sb_sunquan", "dc_sunquan", "xin_sunquan", "jd_sb_sunquan", "ty_sunquan"],
	zhouyu: ["zhouyu", "re_zhouyu", "dc_sb_zhouyu", "yue_zhouyu", "sb_zhouyu", "ps1062_zhouyu", "ps2080_zhouyu", "jx_zhouyu"],
	luxun: ["luxun", "re_luxun", "jsrg_luxun", "sb_luxun", "ty_luxun", "huan_luxun"],
	lvmeng: ["lvmeng", "re_lvmeng", "sb_lvmeng", "sp_lvmeng"],
	huanggai: ["huanggai", "re_huanggai", "sb_huanggai", "dc_sb_huanggai"],
	daqiao: ["daqiao", "re_daqiao", "sb_daqiao", "jd_sb_daqiao", "yue_daqiao", "sp_daqiao"],
	sunshangxiang: ["sunshangxiang", "re_sunshangxiang", "jsrg_sunshangxiang", "star_sunshangxiang", "sp_sunshangxiang", "sb_sunshangxiang", "jd_sb_sunshangxiang"],
	ganning: ["ganning", "re_ganning", "sb_ganning", "yongjian_ganning", "jd_sb_ganning", "ty_ganning"],
	yj_ganning: ["yj_ganning", "sp_ganning"],
	lvbu: ["lvbu", "re_lvbu", "jsrg_lvbu", "ps_lvbu", "ol_jsrg_lvbu"],
	diaochan: ["diaochan", "re_diaochan", "sb_diaochan", "sp_diaochan", "yue_diaochan"],
	huatuo: ["huatuo", "re_huatuo", "old_huatuo"],
	huaxiong: ["huaxiong", "re_huaxiong", "old_huaxiong", "sb_huaxiong", "ol_huaxiong", "ol_sb_huaxiong"],
	yuanshu: ["yuanshu", "re_yuanshu", "yl_yuanshu", "old_yuanshu", "ol_yuanshu", "star_yuanshu"],
	gongsunzan: ["gongsunzan", "re_gongsunzan", "dc_gongsunzan", "xin_gongsunzan", "sb_gongsunzan", "sp_gongsunzan", "yy_gongsunzan", "ol_sb_gongsunzan"],
	re_lidian: ["re_lidian", "old_re_lidian", "junk_lidian"],
	tw_caocao: ["tw_caocao", "jsrg_caocao", "yj_caocao", "ol_jsrg_caocao"],
	mateng: ["tw_mateng", "mateng", "std_mateng", "dc_mateng"],
	tw_xiahouen: ["tw_xiahouen", "jsrg_xiahouen"],
	jiangji: ["dc_jiangji", "tw_jiangji", "jiangji"],
	baoxin: ["tw_baoxin", "baoxin"],
	yanxiang: ["yanxiang", "tw_yanxiang"],
	liwei: ["liwei", "tw_liwei"],
	tw_jiling: ["jiling", "dc_jiling", "tw_jiling", "std_jiling", "yj_jiling"],
	tw_zhangji: ["tw_zhangji", "ol_tw_zhangji"],
	yuejiu: ["yuejiu", "dc_yuejiu"],
	wenyang: ["wenyang", "db_wenyang", "diy_wenyang", "std_db_wenyang", "jsrg_wenyang"],
	gexuan: ["gexuan", "tw_gexuan"],
	panshu: ["panshu", "re_panshu"],
	yangwan: ["yangwan", "sp_yangwan", "jd_sp_yangwan"],
	sunyi: ["re_sunyi", "sunyi", "tw_sunyi", "std_sunyi"],
	fengfangnv: ["fengfangnv", "re_fengfangnv"],
	luotong: ["dc_luotong", "luotong", "std_dc_luotong", "scl_luotong"],
	dc_wangchang: ["dc_wangchang", "tw_wangchang", "clan_wangchang"],
	guozhao: ["guozhao", "xin_guozhao", "jsrg_guozhao"],
	dingshangwan: ["dingshangwan", "ol_dingshangwan", "huan_dingshangwan"],
	qinghegongzhu: ["qinghegongzhu", "dc_qinghegongzhu"],
	caofang: ["caofang", "jsrg_caofang"],
	caomao: ["caomao", "mb_caomao"],
	sp_zhenji: ["sp_zhenji", "jsrg_zhenji", "mb_sp_zhenji"],
	zhugejin: ["zhugejin", "dc_sb_zhugejin", "sb_zhugejin"],
	caoang: ["caoang", "dc_sb_caoang", "huan_caoang"],
	zhangxiu: ["zhangxiu", "ol_sb_zhangxiu", "dc_sb_zhangxiu", "ns_zhangxiu"],
	yuanji: ["yuanji", "ol_yuanji"],
	zhangfen: ["zhangfen", "mb_zhangfen"],
	dc_tianfeng: ["dc_tianfeng", "tianfeng"],
	caozhi: ["caozhi", "dc_caozhi", "re_caozhi", "ps_caozhi", "ol_caozhi"],
	zhangchunhua: ["zhangchunhua", "re_zhangchunhua", "ol_zhangchunhua", "jin_zhangchunhua", "star_zhangchunhua"],
	yujin: ["yujin", "yujin_yujin", "ol_yujin", "sb_yujin", "xin_yujin", "re_yujin", "jd_sb_yujin", "tw_yujin"],
	dc_xushu: ["re_xushu", "dc_xushu", "xia_xushu"],
	xushu: ["xin_xushu", "xushu", "std_xushu"],
	fazheng: ["xin_fazheng", "ol_fazheng", "re_fazheng", "sb_fazheng", "tw_re_fazheng", "fazheng", "jd_sb_fazheng", "star_fazheng"],
	masu: ["xin_masu", "re_masu", "masu"],
	xusheng: ["xusheng", "xin_xusheng", "re_xusheng", "old_xusheng"],
	wuguotai: ["wuguotai", "xin_wuguotai", "re_wuguotai", "ol_wuguotai"],
	lingtong: ["lingtong", "xin_lingtong", "ol_lingtong", "re_lingtong", "old_lingtong"],
	gaoshun: ["gaoshun", "xin_gaoshun", "ol_gaoshun", "re_gaoshun", "sb_gaoshun", "old_gaoshun"],
	zhonghui: ["zhonghui", "xin_zhonghui", "re_zhonghui", "old_zhonghui", "pe_zhonghui", "clan_zhonghui", "yj_zhonghui", "std_zhonghui"],
	wangyi: ["wangyi", "ol_wangyi", "re_wangyi", "old_wangyi"],
	caozhang: ["caozhang", "ol_caozhang", "re_caozhang", "xin_caozhang"],
	guanzhang: ["guanzhang", "re_guanzhang", "old_guanzhang"],
	madai: ["old_madai", "re_madai", "tw_madai", "madai"],
	liaohua: ["liaohua", "re_liaohua", "xin_liaohua", "ty_liaohua"],
	bulianshi: ["bulianshi", "dc_bulianshi", "re_bulianshi", "old_bulianshi"],
	handang: ["handang", "xin_handang", "re_handang", "tw_handang", "sb_handang", "old_handang"],
	chengpu: ["chengpu", "ol_chengpu", "re_chengpu", "xin_chengpu", "tw_chengpu", "ns_chengpu", "std_chengpu"],
	liubiao: ["liubiao", "xin_liubiao", "re_liubiao", "jsrg_liubiao", "sb_liubiao", "oldre_liubiao", "old_liubiao", "ol_liubiao", "std_liubiao"],
	manchong: ["manchong", "re_manchong"],
	caochong: ["caochong", "re_caochong", "old_caochong", "ol_caochong"],
	guohuai: ["guohuai", "re_guohuai", "xin_guohuai", "tw_guohuai", "sb_guohuai"],
	jianyong: ["jianyong", "ol_jianyong", "re_jianyong", "xin_jianyong"],
	panzhangmazhong: ["panzhangmazhong", "re_panzhangmazhong", "xin_panzhangmazhong"],
	yufan: ["yufan", "ol_yufan", "xin_yufan", "re_yufan"],
	zhuran: ["zhuran", "re_zhuran", "xin_zhuran", "old_zhuran"],
	liru: ["xin_liru", "liru", "dc_liru", "re_liru", "yj_liru", "ol_liru", "std_liru"],
	fuhuanghou: ["fuhuanghou", "re_fuhuanghou", "xin_fuhuanghou", "tw_fuhuanghou", "old_fuhuanghou", "std_fuhuanghou"],
	chenqun: ["chenqun", "dc_chenqun", "re_chenqun", "old_chenqun"],
	hanhaoshihuan: ["hanhaoshihuan", "re_hanhaoshihuan"],
	caozhen: ["caozhen", "re_caozhen", "xin_caozhen", "old_caozhen"],
	wuyi: ["wuyi", "re_wuyi", "xin_wuyi", "dc_wuyi"],
	sunluban: ["re_sunluban", "xin_sunluban", "tw_sunluban", "sunluban", "std_sunluban"],
	zhuhuan: ["re_zhuhuan", "xin_zhuhuan", "zhuhuan", "old_zhuhuan"],
	caoxiu: ["caoxiu", "re_caoxiu", "xin_caoxiu", "tw_caoxiu", "old_caoxiu"],
	xiahoushi: ["xiahoushi", "re_xiahoushi", "sb_xiahoushi", "sp_xiahoushi"],
	zhangyi: ["zhangyi", "re_zhangyi", "xin_zhangyi"],
	quancong: ["quancong", "re_quancong", "xin_quancong", "old_quancong", "yy_quancong"],
	sunxiu: ["sunxiu", "re_sunxiu", "xin_sunxiu"],
	zhuzhi: ["zhuzhi", "re_zhuzhi", "xin_zhuzhi", "old_zhuzhi"],
	liuyu: ["liuyu", "dc_liuyu", "ol_liuyu"],
	zhangrang: ["zhangrang", "ol_zhangrang", "junk_zhangrang"],
	jikang: ["jikang", "re_jikang", "dc_jikang"],
	xinxianying: ["xinxianying", "re_xinxianying", "ol_xinxianying", "sp_xinxianying"],
	gongsunyuan: ["gongsunyuan", "re_gongsunyuan", "std_gongsunyuan", "yy_gongsunyuan"],
	zhoucang: ["zhoucang", "re_zhoucang", "xin_zhoucang"],
	guotufengji: ["guotufengji", "re_guotufengji"],
	guanping: ["guanping", "re_guanping", "dc_sb_guanping"],
	caifuren: ["caifuren", "re_caifuren", "xin_caifuren", "ol_caifuren"],
	guyong: ["guyong", "re_guyong", "xin_guyong", "tw_guyong"],
	yj_jushou: ["yj_jushou", "re_jushou", "xin_jushou", "dc_sb_jushou"],
	guohuanghou: ["guohuanghou", "re_guohuanghou", "std_guohuanghou"],
	liuchen: ["liuchen", "re_liuchen", "std_liuchen"],
	liufeng: ["liufeng", "re_liufeng", "huan_liufeng"],
	sundeng: ["sundeng", "re_sundeng", "ns_sundeng"],
	caiyong: ["caiyong", "re_caiyong", "yue_caiyong"],
	chengong: ["chengong", "re_chengong", "sb_chengong"],
	xunyou: ["xunyou", "re_xunyou", "clan_xunyou"],
	xuezong: ["xuezong", "tw_xuezong", "std_xuezong", "mb_xuezong"],
	huanghao: ["huanghao", "dc_huanghao", "old_huanghao"],
	caorui: ["caorui", "re_caorui", "old_caorui", "yy_caorui", "std_caorui"],
	sunziliufang: ["sunziliufang", "dc_sunziliufang"],
	liyan: ["liyan", "old_liyan"],
	zhangsong: ["zhangsong", "re_zhangsong"],
	zhongyao: ["zhongyao", "re_zhongyao", "clan_zhongyao"],
	liwan: ["ol_liwan", "liwan"],
	wuxian: ["wuxian", "clan_wuxian"],
	simafu: ["mb_simafu", "simafu", "yj_simafu"],
	xuangongzhu: ["yj_xuangongzhu", "xuangongzhu"],
	cenhun: ["cenhun", "std_cenhun"],
	jin_yanghu: ["jin_yanghu", "dc_yanghu", "sp_yanghu", "std_dc_yanghu"],
	jiachong: ["dc_jiachong", "jin_jiachong", "jiachong", "mb_jiachong"],
	yangyan: ["yangyan", "old_yangyan"],
	yangzhi: ["yangzhi", "old_yangzhi"],
	zhongyan: ["zhongyan", "clan_zhongyan"],
	simazhou: ["simazhou", "mb_simazhou"],
	jin_xiahouhui: ["jin_xiahouhui", "jd_jin_xiahouhui"],
};
